CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    CONSTRAINT username_format CHECK (username ~ '^[a-z0-9_]{3,30}$')
);

CREATE TABLE conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(10) NOT NULL CHECK (kind IN ('DIRECT', 'GROUP')),
    user_low_id BIGINT REFERENCES app_user(id),
    user_high_id BIGINT REFERENCES app_user(id),
    CONSTRAINT direct_pair CHECK (
        (kind = 'DIRECT' AND user_low_id IS NOT NULL AND user_high_id IS NOT NULL AND user_low_id < user_high_id)
        OR (kind = 'GROUP' AND user_low_id IS NULL AND user_high_id IS NULL)
    ),
    CONSTRAINT one_direct_thread UNIQUE (user_low_id, user_high_id)
);

CREATE TABLE conversation_participant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversation(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    CONSTRAINT one_membership UNIQUE (conversation_id, user_id)
);
CREATE INDEX participant_by_user ON conversation_participant (user_id, conversation_id);

CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversation(id),
    sender_id BIGINT NOT NULL REFERENCES app_user(id),
    body VARCHAR(2000) NOT NULL CHECK (length(trim(body)) > 0),
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX message_by_conversation ON chat_message (conversation_id, id DESC);
